name: coriander_player
description: A new Flutter project.
publish_to: 'none'
version: 1.5.1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.0.1 
  material_color_utilities: ^0.11.1
  window_manager: ^0.3.8
  provider: ^6.1.1
  rust_builder:
    path: rust_builder
  flutter_rust_bridge: ^2.4.0
  path_provider: ^2.0.15
  flutter_localizations:
    sdk: flutter
  ffi: ^2.1.0
  path: ^1.8.3
  material_symbols_icons: ^4.2719.1
  github: ^9.24.0
  flutter_markdown: ^0.7.1
  flex_color_picker: ^3.5.0
  filepicker_windows: ^2.1.4
  desktop_lyric:
    git:
      url: https://github.com/Ferry-200/desktop_lyric.git
      ref: 536be8df55c80a7fdf7cc20f603d3fc76a732821
  music_api:
    git:
      url: https://github.com/Ferry-200/music_api_dart.git
      ref: c6f3e0abd9c6295b3678ce10d30bc09debda9abe
  pinyin: ^3.3.0
  hotkey_manager: ^0.2.3
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  integration_test:
    sdk: flutter
  ffigen: ^14.0.1

flutter:
  uses-material-design: true
  assets:
    - app_icon.ico