name: coriander_player
description: A new Flutter project.
publish_to: 'none'
version: 1.0.1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.0.1 
  material_color_utilities: 0.8.0
  window_manager: ^0.3.8
  provider: ^6.1.1
  rust_builder:
    path: rust_builder
  flutter_rust_bridge: 2.0.0-dev.32
  path_provider: ^2.0.15
  flutter_localizations:
    sdk: flutter
  ffi: ^2.1.0
  path: ^1.8.3
  material_symbols_icons: ^4.2719.1

  # music_api
  encrypt: ^5.0.3
  meta: ^1.10.0
  pointycastle: ^3.7.4
  crypto: ^3.0.3
  xml: ^6.5.0
  collection: ^1.18.0
  
  github: ^9.24.0
  flutter_markdown: ^0.7.1
  flex_color_picker: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - app_icon.ico