name: 新功能请求
description: 请求为程序添加新功能
title: "[新功能] "
labels: [enhancement]

body:
  - type: markdown
    attributes:
      value: |
        **请描述你想要添加的新功能，并指出它可以带来什么。**

  - type: dropdown
    id: pull_request
    attributes:
      label: 附带PR？
      description: |
        是否自行提交Pull Request解决此issue
        如果你不是开发者，请忽略此项
      options:
        - "否"
        - "是"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 功能描述
      description: 描述你想要添加的新功能
      placeholder: |
        描述你想要添加的新功能
        如果附带PR，请说明你要如何实现这个功能
    validations:
      required: true

  - type: input
    id: type
    attributes:
      label: 新功能的分类（选填）
      description: 功能属于哪个分类
      placeholder: 如：UI、桌面歌词、专辑、播放列表等
    validations:
      required: false

