// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `_init_controls`, `_new`, `_ras_ref_from_pic_data`, `_update_display`, `_update_state`, `_update_time_properties`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SMTCFlutter>>
abstract class SmtcFlutter implements RustOpaqueInterface {
  /// Apis for Flutter
  Future<void> close();

  /// Apis for Flutter
  factory SmtcFlutter() =>
      RustLib.instance.api.crateApiSmtcFlutterSmtcFlutterNew();

  /// Apis for Flutter
  Stream<SMTCControlEvent> subscribeToControlEvents();

  /// Apis for Flutter
  Future<void> updateDisplay(
      {required String title,
      required String artist,
      required String album,
      required int duration,
      required String path});

  /// Apis for Flutter
  Future<void> updateState({required SMTCState state});

  /// progress, duration: ms
  /// Apis for Flutter
  Future<void> updateTimeProperties({required int progress});
}

enum SMTCControlEvent {
  play,
  pause,
  previous,
  next,
  unknown,
  ;
}

enum SMTCState {
  paused,
  playing,
  ;
}
