// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.32.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class SystemTheme {
  /// a, r, g, b
  final (int, int, int, int) fore;

  /// a, r, g, b
  final (int, int, int, int) accent;

  const SystemTheme({
    required this.fore,
    required this.accent,
  });

  static SystemTheme getSystemTheme({dynamic hint}) =>
      RustLib.instance.api.systemThemeGetSystemTheme(hint: hint);

  static Stream<SystemTheme> onSystemThemeChanged({dynamic hint}) =>
      RustLib.instance.api.systemThemeOnSystemThemeChanged(hint: hint);

  @override
  int get hashCode => fore.hashCode ^ accent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SystemTheme &&
          runtimeType == other.runtimeType &&
          fore == other.fore &&
          accent == other.accent;
}
