// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.32.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// path: 文件或文件夹的绝对路径。
/// 会打开父级目录并选择路径指向的项。
Future<bool> showInExplorer({required String path, dynamic hint}) =>
    RustLib.instance.api.showInExplorer(path: path, hint: hint);

Future<String?> pickSingleFolder({dynamic hint}) =>
    RustLib.instance.api.pickSingleFolder(hint: hint);

Future<bool> launchInBrowser({required String uri, dynamic hint}) =>
    RustLib.instance.api.launchInBrowser(uri: uri, hint: hint);
